# Generated by Django 5.2.6 on 2025-09-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoty',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('footwear', 'Footwear'), ('equipment', 'Equipment'), ('apparel', 'Apparel'), ('women', 'Women'), ('men', 'Men'), ('kids', 'Kids'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
