# Generated by Django 5.2.6 on 2025-09-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('footwear', 'Footwear'), ('equipment', 'Equipment'), ('apparel', 'Apparel')], default='general', max_length=20),
        ),
    ]
